name: LucianoPulido

services:
  frontend:
    container_name: lucianopulido-frontend
    image: lucianopulido-frontend-image
    build: 
      context: ./Frontend
      dockerfile: dockerfile.dev
    volumes:
      - "./Frontend:/app"
    ports:
      - "5173:5173"
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && npm run dev"
    depends_on:
      - backend
  
  backend:
    container_name: lucianopulido-backend
    image: lucianopulido-backend-image
    build: 
      context: ./Backend/LucianoPulido
      dockerfile: dockerfile.dev
    volumes:
      - "./Backend/LucianoPulido:/app"
    ports:
      - "8080:8080"
    env_file:
      - .env.local.backend
    depends_on:
      - database
  
  database:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.local.database
    volumes:
      - lucianopulido-database-volume:/var/lib/postgresql/data

volumes:
  lucianopulido-database-volume:
