name: LucianoPulido

services:
  frontend:
    container_name: lucianopulido-frontend
    image: lucianopulido-frontend-image
    build: 
      context: ./frontend
      dockerfile: dockerfile.dev
    volumes:
      - "./frontend:/app"
    ports:
      - "5173:5173"
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && npm run dev"
    depends_on:
      - backend
  
  backend:
    container_name: lucianopulido-backend
    image: lucianopulido-backend-image
    build: 
      context: ./Backend/LucianoPulido
      dockerfile: dockerfile.dev
    volumes:
      - "./backend/LucianoPulido:/app"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/LucianoPulido
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=POSTGRESQL
    depends_on:
      - database
  
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: LucianoPulido
    volumes:
      - lucianopulido-database-volume:/var/lib/postgresql/data

volumes:
  lucianopulido-database-volume:
