FROM eclipse-temurin:17-jdk-focal
WORKDIR /app
COPY .mvn/ ./.mvn
COPY mvnw pom.xml ./
RUN chmod 777 ./mvnw
RUN ./mvnw dependency:go-offline
COPY src ./src
RUN chmod 777 /__cacert_entrypoint.sh
CMD ["./mvnw", "spring-boot:run"]